grails-app/controllers/bank_app/EmployeeController.groovy
package bank_app

import grails.plugin.springsecurity.annotation.Secured

/**
 * A controller for ROLE_EMPLOYEE user's view and model
 */
class EmployeeController {

    ManageAccountsService manageAccountsService

    def setChecked = true
    def completeChecked = true
    def declinedChecked = true

    /**
     * Filter system's Bank Orders based on order status
     */
    @Secured("hasRole('ROLE_EMPLOYEE')")
    def filter() {
        setChecked = params.setChecked
        completeChecked = params.completeChecked
        declinedChecked = params.declinedChecked
        redirect(action: "index")
    }

    /**
     * Generate sorted system orders table based on order status filters
     */
    @Secured("hasRole('ROLE_EMPLOYEE')")
    def index() {
        def orders = BankOrder.listOrderByDateCreated(order: "asc").findAll {
            (setChecked? it.status == Status.SET : false) ||
                    (completeChecked? it.status == Status.COMPLETE : false) ||
                    (declinedChecked? it.status == Status.DECLINED : false)
        }

        render(view: "index", model: [orders: orders, setChecked: setChecked, completeChecked: completeChecked, declinedChecked: declinedChecked])
    }

    /**
     * Generate order detail view
     */
    @Secured("hasRole('ROLE_EMPLOYEE')")
    def order() {
        def order = BankOrder.get(params.id)
        render(view: "order", model: [order: order])
    }

    /**
     * Approve order
     */
    @Secured("hasRole('ROLE_EMPLOYEE')")
    def approveOrder() {
        flash.message = manageAccountsService.approveOrder(BankOrder.get(params.id))
        redirect(action: "order", id: params.id)
    }

    /**
     * Decline order
     */
    @Secured("hasRole('ROLE_EMPLOYEE')")
    def declineOrder () {
        flash.message = manageAccountsService.declineOrder(BankOrder.get(params.id))
        redirect(action: "order", id: params.id)
    }
}

grails-app/views/employee/index.gsp
<html>
<head>
    <meta name="layout" content="main"/>
    <title>Orders</title>
</head>
<body>

<div id="content" role="main">

    <div class="text-center padding-around">
        <g:form name="statusForm" controller="employee">
            <g:checkBox name="setChecked" value="${setChecked}" />SET
            <g:checkBox name="completeChecked" value="${completeChecked}" />COMPLETE
            <g:checkBox name="declinedChecked" value="${declinedChecked}" />DECLINED
            <g:actionSubmit value="FILTER" action="filter" class="btn btn-primary"/>
        </g:form>
    </div>

    <div class="container" style="margin-bottom: 25px;">

        <g:if test="${orders.size() > 0}">
            <div class="table-responsive ">
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th>Account Sender</th>
                        <th>Account Receiver</th>
                        <th>Date & Time</th>
                        <th>Amount</th>
                        <th>Status</th>
                        <th>Detail</th>
                    </tr>
                    </thead>
                    <tbody>

                    <g:each var="order" in="${orders}">
                        <tr>
                            <td>${order.senderAccount.number}</td>
                            <td>${order.receiverAccount.number}</td>
                            <td><g:formatDate date="${order.dateCreated}" type="datetime" style="MEDIUM"/></td>
                            <td>${order.amount}</td>
                            <td>${order.status}</td>
                            <td><g:link class="btn btn-primary" action="order" id="${order.id}">Detail</g:link></td>
                        </tr>
                    </g:each>

                    </tbody>
                </table>
            </div>
        </g:if>

        <g:if test="${orders.size() == 0}">
            <div class="alert alert-info" style="margin: 0px; padding: 0px; padding-left: 5px;">
                <strong>No orders to show</strong>
            </div>
        </g:if>

    </div>

</div>
</body>
</html>

grails-app/views/employee/order.gsp
<%@ page import="bank_app.Status" %>
<html>
<head>
    <meta name="layout" content="main"/>
    <title>Order Detail</title>

</head>
<body>

<div id="content" role="main">

    <div class="container" style="margin-bottom: 25px;">

        <ul class="list-group text-center section">
            <li class="list-group-item row detailRow"><div class="col-md-6 bg-primary field">Sender Username</div><div class="col-md-6 field">${order.senderAccount.user.username}</div></li>
            <li class="list-group-item row detailRow"><div class="col-md-6 bg-primary field">Sender Acc Number</div><div class="col-md-6 field">${order.senderAccount.number}</div></li>
            <li class="list-group-item row detailRow"><div class="col-md-6 bg-primary field">Receiver Username</div><div class="col-md-6 field">${order.receiverAccount.user.username}</div></li>
            <li class="list-group-item row detailRow"><div class="col-md-6 bg-primary field">Receiver Acc Number</div><div class="col-md-6 field">${order.receiverAccount.number}</div></li>
            <li class="list-group-item row detailRow"><div class="col-md-6 bg-primary field">Order Amount</div><div class="col-md-6 field">${order.amount}</div></li>
            <li class="list-group-item row detailRow"><div class="col-md-6 bg-primary field">Order Status</div><div class="col-md-6 field">${order.status}</div></li>
            <li class="list-group-item row detailRow"><div class="col-md-6 bg-primary field">Order Created</div><div class="col-md-6 field"><g:formatDate date="${order.dateCreated}" type="datetime" style="MEDIUM"/></div></li>
        </ul>

        <g:if test="${order.status == bank_app.Status.SET}">
            <div class="text-center tbuttons">
                <a class="btn btn-danger" role="button" href="${createLink(action: "declineOrder", id: order.id)}">
                    Decline
                </a>

                <a class="btn btn-primary" role="button" href="${createLink(action: 'approveOrder', id: order.id)}">
                    Approve
                </a>
            </div>
        </g:if>

        <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
        </g:if>

    </div>

</div>
</body>
</html>